#!/bin/sh
# POSTINST script for weatherflowtempestsvglogger

echo "\033[36m HI I'M A POSTINST SCRIPT `date +"%s"` \033[39m"
systemctl daemon-reload
systemctl enable weatherflowtempestsvglogger.service
systemctl start weatherflowtempestsvglogger.service

exit 0