#!/bin/sh
# PRERM script for weatherflowtempestsvglogger

echo "\033[36m HI I'M A PRERM SCRIPT `date --rfc-3339='seconds'` \033[39m"
systemctl stop weatherflowtempestsvglogger.service
systemctl disable weatherflowtempestsvglogger.service

exit 0